### ISSUE TITLE
Status Message is not always helpful

### ISSUE THREAD

**Issue by nagelfargithub** [modular-mind/updatemanager#3]
There is an issue reading from my p2 location:
`Failed to load metadata repository at location http://xxx.com/something/p2/`
Unfortunately the status is not very helpful, it looks like this in the log
`Status severity=4, message=, code=0`
As the exception is contained in the Status Object I suggest printing the full exception when the message is "null" as seems to be the case here.

**Comment by nagelfargithub** [comment]
I believe that the exception itself is the same as described at https://www.eclipse.org/forums/index.php/t/367402/

**Comment by modular-mind** [comment]
I'm now logging the exception for the status. Let me know if this helps.

**Comment by nagelfargithub** [comment]
I can now inject my own Logger and exceptions get logged as expected.
